# Generated by Django 5.1.2 on 2024-11-11 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_availabletime_remove_booking_booking_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('9:00 AM', '9:00 AM'), ('12:00 PM', '12:00 PM'), ('3:00 PM', '3:00 PM'), ('6:00 PM', '6:00 PM')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.availabledate'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'time_slot')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.DeleteModel(
            name='AvailableTime',
        ),
    ]
